### ISSUE TITLE
Position View: If mark price less than liq price, hide position

### ISSUE THREAD

**Issue by harshasomisetty** [harshasomisetty/perps-ui#51]
Should ordinarily run liquidator bot

**Comment by askibin** [comment]
I don't think you should hide it. User can choose to close such position manually. And more importantly if position is not liquidated and price bounces back then the user can see a new position suddenly pops up from nowhere (if a liquidator failed to close it promptly)

**Comment by harshasomisetty** [comment]
sure, will keep as is then
