### ISSUE TITLE
Missing token in the user's wallet is not handled properly

### ISSUE THREAD

**Issue by askibin** [harshasomisetty/perps-ui#55]
dots are displayed instead of the zero balance
and black zero in place of the MAX button
![image](https://user-images.githubusercontent.com/49493810/226376779-87a032a4-bf3a-4f48-afb8-484583d485a1.png)

**Comment by harshasomisetty** [comment]
The dots are fixed in 59d1a4a579a988771fa19d2b5333ffa377399b19

Could you clarify what to do with the max button when the user doesn't have a token?

**Comment by askibin** [comment]
whatever is easier, you can remove it or disable, just do not display that black 0

**Comment by harshasomisetty** [comment]
fixed in 9c35f46c54809c3db346c611264dc5df9298dd4b
