### ISSUE TITLE
 "You Pay" / "Your Long" / Leverage relationship doesn't work properly if tokens are different

### ISSUE THREAD

**Issue by askibin** [harshasomisetty/perps-ui#56]

**Comment by harshasomisetty** [comment]
could you clarify what isn't working? at the moment the you pay token is converted to the your long token value, then the open position is performed. the leverage reflects the price of "you pay" token after its converted to "your long" token

**Comment by askibin** [comment]
"You pay" - $77.67
"Your Long" - $192.10
Leverage - 10x
how is this possible? leverage should be ~2.5 in this case
