### ISSUE TITLE
If ATA is missing swap fails, needs pre-instruction to create an ATA

### ISSUE THREAD

**Issue by askibin** [harshasomisetty/perps-ui#58]
> Program logged: "Instruction: Swap"
> Program logged: "AnchorError caused by account: receiving_account. Error Code: AccountNotInitialized. Error Number: 3012. Error Message: The program expected this account to be already initialized."
> Program consumed: 6969 of 400000 compute units
> Program returned error: "custom program error: 0xbc4"

**Comment by harshasomisetty** [comment]
fixed 87a525396f2837075765493ed7ff6b2b48d4a8fe
