### ISSUE TITLE
Wallet balance doesn't match what is displayed in "You Pay"

### ISSUE THREAD

**Issue by askibin** [harshasomisetty/perps-ui#62]
Sum in the wallet: 2.6344
Displayed: 2.74
![image](https://user-images.githubusercontent.com/49493810/226387424-ac044e28-091c-4d09-9e03-9e52a6c2f49f.png)

**Comment by harshasomisetty** [comment]
Could this be a one off issue? Not running into that problem, the logic to get a user token balance (for sol specifically), is adding the user's native sol bal plus wrapped sol

https://github.com/harshasomisetty/perps-ui/blob/11aea57daf3ef359aa16dff5d6f6420e1ad85aa8/src/utils/retrieveData.ts#L36

<img width="836" alt="Screenshot 2023-03-20 at 4 40 57 PM" src="https://user-images.githubusercontent.com/25572511/226461017-862d5bab-d4e3-45a3-9086-eb9137064de1.png">
